s3:
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}
  endpoint: ${S3_ENDPOINT}
  bucket: ${S3_BUCKET}
  key-prefix: ${S3_KEY_PREFIX}
  url-expiration-minutes: ${S3_URL_EXPIRATION_MINUTES}